<?php

use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\spectrum\Query\Query;
use Drupal\spectrum\Services\JobService;
use Drupal\spectrum\Triggers\ModelTrigger;

function spectrum_entity_presave($entity)
{
  ModelTrigger::handle($entity, 'presave');
}

function spectrum_entity_insert($entity)
{
  ModelTrigger::handle($entity, 'insert');
}

function spectrum_entity_update($entity)
{
  ModelTrigger::handle($entity, 'update');
}

function spectrum_entity_predelete($entity)
{
  ModelTrigger::handle($entity, 'predelete');
}

function spectrum_entity_delete($entity)
{
  ModelTrigger::handle($entity, 'delete');
}

// We need the Alter query hook to parse expressions that were added to the Spectrum Query
function spectrum_query_spectrum_query_alter(AlterableInterface $drupalQuery)
{
  /** @var Query $query */
  $query = $drupalQuery->getMetaData('spectrum_query');
  $query->parseExpressions($drupalQuery);
}

/**
 * Implements hook_query_tag_alter().
 *
 * @param \Drupal\Core\Database\Query\AlterableInterface $drupalQuery
 */
function spectrum_query_spectrum_query_use_access_policy_alter(AlterableInterface $drupalQuery)
{
  /** @var \Drupal\spectrum\Query\ModelQuery $query */
  $query = $drupalQuery->getMetaData('spectrum_query');
  $query->executeAccessPolicy($drupalQuery);
}
